# Generated by Django 3.0.6 on 2020-05-09 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('ball_values', models.CharField(max_length=21)),
                ('frame_scores', models.CharField(max_length=40, validators=[django.core.validators.int_list_validator])),
                ('lane', models.PositiveIntegerField()),
            ],
        ),
    ]
