# Generated by Django 3.0.6 on 2020-05-09 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ball_values',
            field=models.CharField(blank=True, default='', max_length=21),
        ),
        migrations.AlterField(
            model_name='game',
            name='frame_scores',
            field=models.CharField(blank=True, default='', max_length=40, validators=[django.core.validators.int_list_validator]),
        ),
    ]
